[project]
name = "banatu"
version = "0.1.0"
description = "Gestor de división de gastos en grupos."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.2",
    "streamlit>=1.49.1",
]
